[WIP DRAFT PR]: Cross chain token
SocketDotTech/socket-plugs pull request #16
Opened 2023-09-12 07:09 UTC by Aniket965

**Please DO NOT MERGE 🚨🚨**

2023-10-10 05:46 UTC, arthcp requested changes

2023-10-10 05:48 UTC, Aniket965 commented on src/CrossChainToken/CrossChainToken.sol
> +
it is coz we need to transfer ownership in contract itself  to owner

2023-10-10 05:48 UTC, Aniket965 commented on src/CrossChainToken/CrossChainToken.sol
> +    ) external payable {
okies,

2023-10-13 05:00 UTC, Aniket965 commented on src/CrossChainToken/CrossChainToken.sol
> +            pendingMints[msg.sender][receiver][identifier] += pendingAmount;
✅

2023-10-13 05:01 UTC, Aniket965 commented on src/CrossChainToken/DeployCrossChainTokenStack.sol
> +        );
yes they can't deploy it again with the same details

2023-10-13 05:04 UTC, Aniket965 commented on src/CrossChainToken/DeployCrossChainTokenStack.sol
> +    function deployMultiChain(DeployToChains calldata data) external payable {
i don't know bros why will someone pass excess here

2023-10-13 05:05 UTC, Aniket965 commented on src/CrossChainToken/DeployCrossChainTokenStack.sol
> +                    msg.sender,
good catch I recently added this msg.sender will handle it

2023-10-13 05:08 UTC, Aniket965 commented on test/CrossChainToken.t.sol
> +
okies

2023-10-13 05:10 UTC, Aniket965 commented on src/CrossChainToken/DeployCrossChainTokenStack.sol
> +    event ControllerDeployed(address controller, address token);
removed

2023-10-13 05:11 UTC, Aniket965 commented on src/CrossChainToken/DeployCrossChainTokenStack.sol
> +                emit ConnectorDeployedAndConnected(
fixed

2023-10-13 05:11 UTC, Aniket965 commented on src/CrossChainToken/DeployCrossChainTokenStack.sol
> +                );
we only let 1 deployment per sender

2023-10-13 05:12 UTC, Aniket965 commented on src/CrossChainToken/DeployCrossChainTokenStack.sol
> +                );
with same details

2023-10-13 05:20 UTC, Aniket965 commented on src/CrossChainToken/DeployCrossChainTokenStack.sol
> +                connector.connect(address(connector), switchboard, switchboard);
dones

2023-10-13 05:21 UTC, Aniket965 commented on src/CrossChainToken/DeployCrossChainTokenStack.sol
> +    function deployMultiChain(DeployToChains calldata data) external payable {
let me know if you still want me to add, i will sum(data.values) and send rest of msg.value back

2023-10-18 13:19 UTC, arthcp commented on src/CrossChainToken/DeployCrossChainTokenStack.sol
> +    function deployMultiChain(DeployToChains calldata data) external payable {
mostly by mistake

2024-03-27 10:11 UTC, arthcp commented
stale

2024-03-27 10:11 UTC, closed without merging